services:
  - type: web
    name: bijo-portfolio-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: bijo_portfolio
      - key: CORS_ORIGINS
        value: https://bijo-portfolio.vercel.app
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /api/profile
